name: Deploy site (publish repo root)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare site directory (publish repo root)
        run: |
          set -e
          rm -rf _site
          mkdir -p _site
          # Copy repo files to _site, excluding git metadata and workflows
          rsync -av --exclude='.git' --exclude='.github' --exclude='node_modules' --exclude='README.md' --exclude='docs' ./ _site/
          # Optionally remove any files you don't want published
          # rm -f _site/buildozer.spec
          # rm -rf _site/OrganizeMe  # uncomment if you don't want to publish that folder

      - name: Show _site contents (debug)
        run: |
          echo "Files to be published:"
          ls -la _site | sed -n '1,120p'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

    deploy:
	    needs: build
			runs-on: ubuntu-latest
			environment:
   	   name: github-pages
			steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4