# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: (disabled) Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["__disabled__"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: echo "Jekyll workflow disabled"
  deploy:
    if: false
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Jekyll workflow disabled"
