name: Build & Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node (optional for build)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Detect & build (if project has package.json)
        run: |
          set -e
          echo "Working dir: $(pwd)"
          rm -rf out
          mkdir -p out
          if [ -f package.json ]; then
            echo "package.json found — running npm ci && npm run build (if build script exists)..."
            npm ci --prefer-offline --no-audit --no-fund
            if npm run | grep -q "build"; then
              npm run build
            else
              echo "No npm build script defined — skipping npm run build."
            fi
            for d in build dist _site public out_dir public_html; do
              if [ -d "$d" ]; then
                echo "Found build folder: $d — copying to out/"
                cp -a "$d"/. out/
                exit 0
              fi
            done
            if [ -d "docs" ]; then
              echo "Found docs/ — copying to out/"
              cp -a docs/. out/
              exit 0
            fi
            echo "No recognized build folder found — copying repo root into out/ (excluding .git)"
            rsync -av --exclude='.git' --exclude='.github' --exclude='node_modules' ./ out/
          else
            echo "No package.json — this looks like a plain static repo."
            if [ -d "docs" ]; then
              echo "Found docs/ — copying to out/"
              cp -a docs/. out/
            else
              echo "Copying repo root into out/ (excluding .git and .github)"
              rsync -av --exclude='.git' --exclude='.github' --exclude='node_modules' ./ out/
            fi
          fi

      - name: Show out contents (debug)
        run: |
          echo "Out directory listing:"
          ls -la out | sed -n '1,200p'

      - name: Setup Pages (configure)
        uses: actions/configure-pages@v5

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages   # ✅ fixed input name
          path: ./out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4